server:
  port: 10086
  servlet:
    context-path: /store
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: db-master
    datasource.db-master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qwer1234
      url: jdbc:mysql://127.0.0.1:30001/b_store?useSSL=false&serverTimezone=UTC
    sharding:
      tables:
        sensitive:
          actual-data-nodes: db-master.sensitive_$->{0..9}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: sensitive_$->{user_id%10}
        book_info:
          actual-data-nodes: db-master.book_info_$->{0..99}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: book_info_$->{user_id%100}
      binding-tables: sensitive,book_info
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10
        min-idle: 0
    timeout: 1000 #ms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        prefetch: 1 #每次只消费一个，防止消息堆积

  #mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cn.domain
logging:
  config: classpath:logback.xml
